---
name: CI

on:
  push:
    branches:
      - 'main'
  pull_request_target:
    types: ['opened', 'reopened']
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    name: Python ${{ matrix.python-version}}
    steps:
      - uses: actions/checkout@v2.5.0

      - name: Set up Python
        uses: actions/setup-python@v2.3.3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip and install dev requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Test
        run: tox
